extends: stylelint-config-standard
plugins:
  - stylelint-order
rules:
  at-rule-no-unknown: null
  no-descending-specificity: null
  order/properties-order:
    - content
    - position
    - top
    - bottom
    - left
    - right
    - z-index
    - float
    - clear
    - display
    - grid-template-columns
    - grid-column-gap
    - grid-template-rows
    - grid-row-gap
    - grid-column
    - grid-column-start
    - grid-column-end
    - grid-row
    - grid-row-start
    - grid-row-end
    - flex
    - flex-basis
    - flex-direction
    - flex-flow
    - flex-grow
    - flex-shrink
    - flex-wrap
    - align-content
    - align-items
    - align-self
    - justify-content
    - order
    - table-layout
    - empty-cells
    - vertical-align
    - box-sizing
    - width
    - max-width
    - min-width
    - height
    - max-height
    - min-height
    - overflow
    - overflow-x
    - overflow-y
    - border
    - border-top
    - border-bottom
    - border-left
    - border-right
    - border-width
    - border-top-width
    - border-bottom-width
    - border-left-width
    - border-right-width
    - border-style
    - border-top-style
    - border-bottom-style
    - border-left-style
    - border-right-style
    - border-color
    - border-top-color
    - border-bottom-color
    - border-left-color
    - border-right-color
    - border-radius
    - border-top-left-radius
    - border-top-right-radius
    - border-bottom-left-radius
    - border-bottom-right-radius
    - border-collapse
    - border-spacing
    - outline
    - outline-width
    - outline-style
    - outline-color
    - margin
    - margin-top
    - margin-bottom
    - margin-left
    - margin-right
    - padding
    - padding-top
    - padding-bottom
    - padding-left
    - padding-right
    - list-style
    - list-style-type
    - list-style-image
    - list-style-position
    - counter-increment
    - counter-reset
    - font
    - font-family
    - font-size
    - font-size-adjust
    - text-size-adjust
    - font-weight
    - font-style
    - font-variant
    - font-stretch
    - direction
    - letter-spacing
    - word-spacing
    - white-space
    - quotes
    - orphans
    - widows
    - line-height
    - text-align
    - text-decoration
    - text-indent
    - text-justify
    - text-overflow
    - text-shadow
    - text-transform
    - color
    - background
    - background-color
    - background-image
    - background-repeat
    - background-position
    - background-attachment
    - background-size
    - background-clip
    - box-shadow
    - opacity
    - visibility
    - clip
    - clip-path
    - transform
    - transform-origin
    - perspective
    - perspective-origin
    - backface-visibility
    - transition
    - transition-property
    - transition-duration
    - transition-timing-function
    - transition-delay
    - animation
    - animation-name
    - animation-duration
    - animation-timing-function
    - animation-delay
    - animation-iteration-count
    - animation-direction
    - animation-fill-mode
    - animation-play-state
    - cursor